# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming_voice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streaming_voice.proto',
  package='vad',
  syntax='proto3',
  serialized_options=b'\n\017com.viettel.vad',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15streaming_voice.proto\x12\x03vad\"!\n\x0cVoiceRequest\x12\x11\n\tbyte_buff\x18\x01 \x01(\x0c\">\n\tTextReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\r\n\x05\x66inal\x18\x03 \x01(\x08\x32v\n\x0bStreamVoice\x12\x34\n\tSendVoice\x12\x11.vad.VoiceRequest\x1a\x0e.vad.TextReply\"\x00(\x01\x30\x01\x12\x31\n\x08SendFile\x12\x11.vad.VoiceRequest\x1a\x0e.vad.TextReply\"\x00(\x01\x42\x11\n\x0f\x63om.viettel.vadb\x06proto3'
)




_VOICEREQUEST = _descriptor.Descriptor(
  name='VoiceRequest',
  full_name='vad.VoiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_buff', full_name='vad.VoiceRequest.byte_buff', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=63,
)


_TEXTREPLY = _descriptor.Descriptor(
  name='TextReply',
  full_name='vad.TextReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='vad.TextReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transcript', full_name='vad.TextReply.transcript', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='final', full_name='vad.TextReply.final', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['VoiceRequest'] = _VOICEREQUEST
DESCRIPTOR.message_types_by_name['TextReply'] = _TEXTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoiceRequest = _reflection.GeneratedProtocolMessageType('VoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOICEREQUEST,
  '__module__' : 'streaming_voice_pb2'
  # @@protoc_insertion_point(class_scope:vad.VoiceRequest)
  })
_sym_db.RegisterMessage(VoiceRequest)

TextReply = _reflection.GeneratedProtocolMessageType('TextReply', (_message.Message,), {
  'DESCRIPTOR' : _TEXTREPLY,
  '__module__' : 'streaming_voice_pb2'
  # @@protoc_insertion_point(class_scope:vad.TextReply)
  })
_sym_db.RegisterMessage(TextReply)


DESCRIPTOR._options = None

_STREAMVOICE = _descriptor.ServiceDescriptor(
  name='StreamVoice',
  full_name='vad.StreamVoice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendVoice',
    full_name='vad.StreamVoice.SendVoice',
    index=0,
    containing_service=None,
    input_type=_VOICEREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendFile',
    full_name='vad.StreamVoice.SendFile',
    index=1,
    containing_service=None,
    input_type=_VOICEREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMVOICE)

DESCRIPTOR.services_by_name['StreamVoice'] = _STREAMVOICE

# @@protoc_insertion_point(module_scope)
